name: Bug Report
description: File a bug report
title: ""
labels: ["bug", "triage"]
assignees:
body:
  - type: markdown
    attributes:
      label: Summary
  - type: markdown
    attributes:
      label: Steps to reproduce
      value: 1. ...
  - type: markdown
    attributes:
      label: Expected behaviour
  - type: markdown
    attributes:
      label: Actual behaviour
  - type: textarea
    attributes:
      label: Elixir/Erlang version
      description: "`elixir -v`"
  - type: textarea
    attributes:
      label: Flop and Ecto versions
      description: "`mix deps | grep 'flop\|ecto'`"
  - type: markdown
    attributes:
      label: Additional context
